config/routes.rb
Lumlate::Application.routes.draw do
  get "home/index"

  devise_for :users

  resources :deals do
    resources :votes, :only => :create
  end

  match 'deals_by_max_or_min_value' => 'deals#deal_emails_by_max_or_min_value'
  match 'deals_by_expiry_date' => 'deals#deal_emails_by_expiry_date'
  match 'deals_with_last_expiry_date' => 'deals#deal_emails_with_last_expiry_date'
  match 'deals_by_companies' => 'deals#deal_emails_by_companies'
  match 'deals_with_tags' => 'deals#deal_emails_with_tags'
  match 'deals_by_rating' => 'deals#deal_emails_by_rating'
  match 'deals_in_value_range' => 'deals#deal_emails_in_value_range'

  root :to => "home#index"

end

app/models/deal.rb
class Deal < ActiveRecord::Base
  cattr_reader :per_page
  @@per_page = 10

  belongs_to :company
  belongs_to :subscription
  belongs_to :deal_type
  has_many :emails
  has_many :votes

  validates_associated :company
  validates_associated :deal_type
  validates :title, :presence => true

  acts_as_taggable_on :tags

  def recalc
    update_attribute(:rating, votes.average(:rating).to_i)
  end

  def slug
    title.parameterize()
  end

  def to_label
    title
  end

  def time_left
    expiry
  end
end

app/models/deal_type.rb
class DealType < ActiveRecord::Base
  has_many :deals
end

app/controllers/admin/deals_controller.rb
class Admin::DealsController < Admin::ResourcesController
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @deal_email_type = EmailType.find_by_name("Deal");

    # Paginating deal_emails
    # NOTE: basic pagination like (will_paginate or kaminari) not support multiple
    # paginating for one Model (in our case, Email), so we use simple 'hand made'
    # pagination, showed below. In addition, this code runs faster! =)
    per_page = 10
    if params[:page].present?
      @page = params[:page].to_i
      sleep(2)
    else
      @page = 1
    end
    deal_emails = current_user.deal_emails_by_expiry_date[0...50]
    @pages_count = (deal_emails.count / per_page) + (deal_emails.count % per_page)
    @deal_emails = deal_emails[((@page - 1) * per_page)...(@page * per_page)]

    # Sorting companies by deals count and define top 5 and other companies
    user_companies = current_user.deals.map { |s| s.company }.uniq
    companies = Company.sorted_by_max_deal_count(user_companies)
    @top_companies = companies[0..4]
    @top_companies.each { |c| companies.delete(c) }
    @other_companies = companies

    # Define all user's deals tags
    tags = current_user.tags
    @first_ten_tags = tags[0..9]
    @first_ten_tags.each { |c| tags.delete(c) }
    @other_tags = tags

    respond_to do |format|
      format.html { render :layout => !request.xhr? }
      format.json { render :json => @deals }
      format.js
    end
  end

  def deal_emails_by_max_or_min_value
    # Get deals sorted by max or min value
    if params[:deals_by_value_filter] == 'max'
      @deal_emails = current_user.deal_emails_by_max_value.
        paginate(:page => params[:page], :per_page => 10)
    else
      @deal_emails = current_user.deal_emails_by_min_value.
        paginate(:page => params[:page], :per_page => 10)
    end

    @load = true if params[:page].present?

    respond_to do |format|
      format.js
    end
  end

  def deal_emails_by_expiry_date
    # Get deals sorted by expiry date
    @deal_emails = current_user.deal_emails_by_expiry_date.
      paginate(:page => params[:page], :per_page => 10)

    @load = true if params[:page].present?

    respond_to do |format|
      format.js
    end
  end

  def deal_emails_with_last_expiry_date
    # Search deal with expiry date
    @deal_emails = current_user.deal_emails_with_expiry_date(params[:deals_with_expiry_date_filter].to_date).
      paginate(:page => params[:page], :per_page => 10)

    @load = true if params[:page].present?

    respond_to do |format|
      format.js
    end
  end

  def deal_emails_by_companies
    # Search deals with companies
    @deal_emails = current_user.deal_emails_by_companies(params[:deals_by_companies_filter]).
      paginate(:page => params[:page], :per_page => 10)

    @load = true if params[:page].present?

    respond_to do |format|
      format.js
    end
  end

  def deal_emails_with_tags
    # Search deals tagged with following tag list
    @deal_emails = current_user.deal_emails_tagged_with(params[:deals_with_tags_filter]).
      paginate(:page => params[:page], :per_page => 10)

    @load = true if params[:page].present?

    respond_to do |format|
      format.js
    end
  end

  def deal_emails_by_rating
    # Get deals sorted by rating
    @deal_emails = current_user.deal_emails_by_rating.
      paginate(:page => params[:page], :per_page => 10)

    @load = true if params[:page].present?

    respond_to do |format|
      format.js
    end
  end

  def deal_emails_in_value_range
    # Get deals in value range
    @deal_emails = current_user.deal_emails_in_value_range(params[:min_value], params[:max_value]).
      paginate(:page => params[:page], :per_page => 10)

    @load = true if params[:page].present?

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_form.html.erb
<h3 class="ui-accordion-header ui-helper-reset ui-state-default ui-corner-all">
  <a href="#"><%= deal_email.subject %></a>
</h3>

<div class="ui-accordion-content ui-helper-reset ui-widget-content ui-corner-bottom deal_info">
   Sent at: <%= deal_email.sent %><br />
  <%= deal_email.deal.title %><br />
  <strong>$</strong> <%= deal_email.deal.maxvalue %><br />
  Will expiry <%= distance_of_time_in_words(Time.now, deal_email.deal.expiry) %><br />
  Company: <%= deal_email.deal.company.name %><br />
  <%= image_tag(deal_email.deal.company.image) %><br />
  Tag list: <%= deal_email.deal.tag_list.join(',') %><br />
  <div class="rate_and_like" id="rate_and_like_<%= deal_email.deal.id %>">
    <div id="deal_like">
      <fb:like href="<%= deals_path %>" layout="button_count" show_faces="false" width="450" font=""></fb:like>
    </div>
    <div id="deal_rate">
      <strong class="rating_title">Rating: </strong>
      <div class="rating_stars" id="stars-wrapper_<%= deal_email.deal.id %>">
        <select name="selrate">
          <option value="1">Very poor</option>
          <option value="2">Not that bad</option>
          <option value="3">Average</option>
          <option value="4" selected="selected">Good</option>
          <option value="5">Perfect</option>
        </select>
      </div>
    </div>
  </div>
</div>

<script src="http://connect.facebook.net/en_US/all.js#xfbml=1"></script>
<script type="text/javascript">

  $(document).ready(function(){

    <!-- Stars ratings logic -->

      $("#stars-wrapper_<%= deal_email.deal.id %>").stars({
        <% if !can_vote?(deal_email.deal.id) %>
          disabled: true,
        <% end %>
        inputType: "select",
	      oneVoteOnly: true,
        captionEl: $("#stars-wrapper2-cap"),
        callback: function(ui, type, value){
        $.ajax({
          type: 'post',
          dataType: 'script',
          url: '/deals/<%=deal_email.deal.id%>/votes',
          data: "vote=" + this.value
          });
        $("#stars-wrapper_<%= deal_email.deal.id %>").stars("select", value);
        }
        });

      $("#stars-wrapper_<%= deal_email.deal.id %>").stars("select", <%= deal_email.deal.rating.to_i %>);

      <!-- Hide rating and like for deal_emails zone when DOM loaded -->

      $('.rate_and_like').hide();

    <!-- Highlighting logic -->

      $('.deal_info').hover(function() {
        $(this).find('.rate_and_like').fadeIn(1000);
        $(this).css("background","#DEF6F7");
      },
      function() {
        $(this).find('.rate_and_like').fadeOut(1000);
        $(this).css("background","white");
      });

  });

</script>

app/views/deals/deal_emails_by_companies.js.erb
<% if @load %>
  $("#deal_emails").append("<%= escape_javascript(render(:partial => 'form', :collection => @deal_emails, :as => :deal_email)) %>");
<% else %>
  $("#deal_emails").html("<%= escape_javascript(render(:partial => 'form', :collection => @deal_emails, :as => :deal_email)) %>");
<% end %>
<% if @deal_emails.blank? %>
  $('#no_records').fadeIn(1000);
  $('a.next').hide();
<% else %>
  $('a.next').show();
  $('#no_records').hide();
<% end %>
$('.rating_stars').stars({
  inputType: "select"
});
$('#hidden_current_page').text("<%= @deal_emails.current_page %>");
$('#hidden_url').text('/deals_by_companies.js?page=');

app/views/deals/deal_emails_by_expiry_date.js.erb
<% if @load %>
  $("#deal_emails").append("<%= escape_javascript(render(:partial => 'form', :collection => @deal_emails, :as => :deal_email)) %>");
<% else %>
  $("#deal_emails").html("<%= escape_javascript(render(:partial => 'form', :collection => @deal_emails, :as => :deal_email)) %>");
<% end %>
<% if @deal_emails.blank? %>
  $('#no_records').fadeIn(1000);
  $('a.next').hide();
<% else %>
  $('a.next').show();
  $('#no_records').hide();
<% end %>
$('.rating_stars').stars({
  inputType: "select"
});
$('#hidden_current_page').text("<%= @deal_emails.current_page %>");
$('#hidden_url').text('/deals_by_expiry_date.js?page=');

app/views/deals/deal_emails_by_max_or_min_value.js.erb
<% if @load %>
  $("#deal_emails").append("<%= escape_javascript(render(:partial => 'form', :collection => @deal_emails, :as => :deal_email)) %>");
<% else %>
  $("#deal_emails").html("<%= escape_javascript(render(:partial => 'form', :collection => @deal_emails, :as => :deal_email)) %>");
<% end %>
<% if @deal_emails.blank? %>
  $('#no_records').fadeIn(1000);
  $('a.next').hide();
<% else %>
  $('a.next').show();
  $('#no_records').hide();
<% end %>
$('.rating_stars').stars({
  inputType: "select"
});
$('#hidden_current_page').text("<%= @deal_emails.current_page %>");
$('#hidden_url').text('/deals_by_max_or_min_value.js?page=');

app/views/deals/deal_emails_by_rating.js.erb
<% if @load %>
  $("#deal_emails").append("<%= escape_javascript(render(:partial => 'form', :collection => @deal_emails, :as => :deal_email)) %>");
<% else %>
  $("#deal_emails").html("<%= escape_javascript(render(:partial => 'form', :collection => @deal_emails, :as => :deal_email)) %>");
<% end %>
<% if @deal_emails.blank? %>
  $('#no_records').fadeIn(1000);
  $('a.next').hide();
<% else %>
  $('a.next').show();
  $('#no_records').hide();
<% end %>
$('.rating_stars').stars({
  inputType: "select"
});
$('#hidden_current_page').text("<%= @deal_emails.current_page %>");
$('#hidden_url').text('/deals_by_rating.js?page=');

app/views/deals/deal_emails_in_value_range.js.erb
<% if @load %>
  $("#deal_emails").append("<%= escape_javascript(render(:partial => 'form', :collection => @deal_emails, :as => :deal_email)) %>");
<% else %>
  $("#deal_emails").html("<%= escape_javascript(render(:partial => 'form', :collection => @deal_emails, :as => :deal_email)) %>");
<% end %>
<% if @deal_emails.blank? %>
  $('#no_records').fadeIn(1000);
  $('a.next').hide();
<% else %>
  $('a.next').show();
  $('#no_records').hide();
<% end %>
$('.rating_stars').stars({
  inputType: "select"
});
$('#hidden_current_page').text("<%= @deal_emails.current_page %>");
$('#hidden_url').text('/deals_in_value_range.js?page=');

app/views/deals/deal_emails_with_last_expiry_date.js.erb
<% if @load %>
  $("#deal_emails").append("<%= escape_javascript(render(:partial => 'form', :collection => @deal_emails, :as => :deal_email)) %>");
<% else %>
  $("#deal_emails").html("<%= escape_javascript(render(:partial => 'form', :collection => @deal_emails, :as => :deal_email)) %>");
<% end %>
<% if @deal_emails.blank? %>
  $('#no_records').fadeIn(1000);
  $('a.next').hide();
<% else %>
  $('a.next').show();
  $('#no_records').hide();
<% end %>
$('.rating_stars').stars({
  inputType: "select"
});
$('#hidden_current_page').text("<%= @deal_emails.current_page %>");
$('#hidden_url').text('/deals_with_last_expiry_date.js?page=');

app/views/deals/deal_emails_with_tags.js.erb
<% if @load %>
  $("#deal_emails").append("<%= escape_javascript(render(:partial => 'form', :collection => @deal_emails, :as => :deal_email)) %>");
<% else %>
  $("#deal_emails").html("<%= escape_javascript(render(:partial => 'form', :collection => @deal_emails, :as => :deal_email)) %>");
<% end %>
<% if @deal_emails.blank? %>
  $('#no_records').fadeIn(1000);
  $('a.next').hide();
<% else %>
  $('a.next').show();
  $('#no_records').hide();
<% end %>
$('.rating_stars').stars({
  inputType: "select"
});
$('#hidden_current_page').text("<%= @deal_emails.current_page %>");
$('#hidden_url').text('/deals_with_tags.js?page=');

app/views/deals/index.html.erb
<div id="deals-feed" class="span-24 last">

  <div class="top_part">
    <div class="deals_sort_by">
      <strong>Sort by:</strong>
      <select id="deals_sort_by">
        <option value="expiry">expiry</option>
        <option value="rating">rating</option>
        <option value="max_deal">max</option>
        <option value="min_deal">min</option>
      </select>
    </div>
  </div>

  <div class="left_filters">
    <div>
      <h3>Filters</h3>
      <div class="deal_value_range">
        <h5>by deal value range:</h5>
        <input type="text" id="amount" /><br />
        <div id="deal_range"></div>
      </div>
      <div>
        <h5>with expiry date:</h5>
        <input type="text" id="deal_expiry_datepicker" value="Select date..." size="15" />
      </div>
      <div>
        <h5>by tags:</h5>
          <ol id="selectable_tags">
            <% @first_ten_tags.each do |tag| %>
              <li class="first_ten_tags"><%= tag %></li>
            <% end %>
            <% @other_tags.each do |tag| %>
              <li class="other_tags"><%= tag %></li>
            <% end %>
          </ol>
          <% if @other_tags.present? %>
            <div style="clear: both;"></div>
            <div id="more_tags">more tags</div>
          <% end %>
      </div>
      <div style="clear: both;"></div>
      <div>
        <h5>by companies:</h5>
          <ol id="selectable_companies">
            <% @top_companies.each do |c| %>
              <li class="top_companies" id="<%= c.id %>"><%= c.name %></li>
              <div style="clear: both; margin: 0;"></div>
            <% end %>
            <% @other_companies.each do |c| %>
              <li class="other_companies" id="<%= c.id %>"><%= c.name %></li>
              <div style="clear: both; margin: 0;"></div>
            <% end %>
          </ol>
          <% if @other_companies.present? %>
            <div style="clear: both;"></div>
            <div id="more_companies">more companies</div>
          <% end %>
      </div>
    </div>
  </div>

  <div class="deals_list" id="deals_list">
    <div id="deal_emails">
      <%= render :partial => 'form', :collection => @deal_emails, :as => :deal_email %>
    </div>
    <div id="no_records"><h5>No deal emails for your condition!</h5></div>
    <%= link_to "Load more", "javascript:void(0);", :class => "next" %>
  </div>

  <div id="hidden_url" style="display:none;"></div>
  <div id="hidden_current_page" style="display:none;"></div>
</div>

<script type="text/javascript">

$(document).ready(function(){

  <!-- Left Column Last ExpiryDate initialize Datapicker -->

    $("#deal_expiry_datepicker").datepicker();

  <!-- Left Column Selectable logic for tags -->

    $("#selectable_tags").selectable({
			stop: function() {
        var tag_names = [];
				$(".ui-selected", this).each(function() {
          tag_names.push($(this).text());
				});
      data = { deals_with_tags_filter: tag_names };
      $.get("<%= deals_with_tags_path %>", data);
			}
    });

  <!-- Left Column Selectable logic for companies -->

    $("#selectable_companies").selectable({
			stop: function() {
        var companies_ids = [];
				$(".ui-selected", this).each(function() {
          companies_ids.push($(this).attr("id"));
				});
      data = { deals_by_companies_filter: companies_ids };
      $.get("<%= deals_by_companies_path %>", data);
			}
    });

  <!-- Left Column more tags logic -->

    $('#more_tags').click(function() {
      current_text = $(this).text();
      if(current_text=='more tags'){
        $(this).text("hide other tags");
        $('.other_tags').fadeIn(1000);
      }
      else {
        $(this).text("more tags");
        $('.other_tags').fadeOut(1000);
      }
    });

  <!-- Left Column more companies logic -->

    $('#more_companies').click(function() {
      current_text = $(this).text();
      if(current_text=='more companies'){
        $(this).text("hide other companies");
        $('.other_companies').fadeIn(1000);
      }
      else {
        $(this).text("more companies");
        $('.other_companies').fadeOut(1000);
      }
    });

  <!-- Left Column Max/Min filters logic -->

    $('#deal_max_filter').click(function() {
      data = { deals_by_value_filter: "max" }
      $.get("<%= deals_by_max_or_min_value_path %>", data);
    });

    $('#deal_min_filter').click(function() {
      data = { deals_by_value_filter: "min" }
      $.get("<%= deals_by_max_or_min_value_path %>", data);
    });

  <!-- Left Column Last ExpiryDate filters logic -->

    $('#deal_expiry_datepicker').change(function () {
      data = { deals_with_expiry_date_filter: $(this).val() }
      $.get("<%= deals_with_last_expiry_date_path %>", data);
    });

  <!-- Left Column Max/Min value slider -->

    $( "#deal_range" ).slider({
			range: true,
			min: parseFloat("<%= current_user.deals_min_value %>"),
			max: parseFloat("<%= current_user.deals_max_value %>"),
			values: [ parseFloat("<%= current_user.deals_min_value %>"), parseFloat("<%= current_user.deals_max_value %>") ],
      stop: function(event, ui) {
        minimum = ui.values[ 0 ];
        maximum = ui.values[ 1 ];
        data = { min_value : minimum, max_value: maximum }
        $.get("<%= deals_in_value_range_path %>", data);
      },
			slide: function( event, ui ) {
				$( "#amount" ).val( "$" + ui.values[ 0 ] + " - $" + ui.values[ 1 ] );
			}
		});
    $( "#amount" ).val( "$" + $( "#deal_range" ).slider( "values", 0 ) + " - $" + $( "#deal_range" ).slider( "values", 1 ) );

  <!-- Top right sort_by_box logic -->

    var first_expiry_sorting = true;

    $("#deals_sort_by").change(function () {
      $("select#deals_sort_by option:selected").each(function () {
        var str = $(this).text();
        if(str=='expiry'){
          if(first_expiry_sorting == true){
            first_expiry_sorting = false;
          }
          else{
            $.get("<%= deals_by_expiry_date_path %>");
          }
        }
        else if(str=='max') {
          data = { deals_by_value_filter: "max" }
          $.get("<%= deals_by_max_or_min_value_path %>", data);
        }
        else if(str=='min') {
          data = { deals_by_value_filter: "min" }
          $.get("<%= deals_by_max_or_min_value_path %>", data);
        }
        else if(str=='rating') {
          $.get("<%= deals_by_rating_path %>");
        }
      });
    }).change();

  <!-- Top Right box initialize select box -->

    $('#deals_sort_by').selectmenu();

  <!-- Feed deal initialize 'more' button -->

    $('a.next').button();

  <!-- Feed deal initialize rating logic >

    $('.rating_stars').stars({
      inputType: "select"
    });

  <!-- Feed deal 'more deals' button logic -->

    var first_case = true;

    $("a.next").click(function() {
      $('span.ui-button-text').html('loading...');
      if(first_case == true ){
        first_case = false;
        var currPage = 1;
        var url = "/deals.js?page=";
      }
      else{
        var currPage = $('#hidden_current_page').text();
        var url = $('#hidden_url').text();
      }
      loadMore(url, ++currPage);
    });

});

  <!-- Feed deal load_more_function logic -->

    function loadMore(url, pageNo) {
      $.get(url + pageNo).success(function() {
        $('html, body').animate({scrollTop: $('#deal_emails').height()}, 800);
        $('span.ui-button-text').html('Load more');
      });
    }

</script>

app/views/deals/index.js.erb
<% if @pages_count > @page %>
    $("#deal_emails").append("<%= escape_javascript(render(:partial => 'form', :collection => @deal_emails, :as => :deal_email)) %>");
    $('#hidden_current_page').text("<%= @page %>");
    $('#hidden_url').text('/deals.js?page=');
<% elsif @pages_count == @page %>
    $("#deal_emails").append("<%= escape_javascript(render(:partial => 'form', :collection => @deal_emails, :as => :deal_email)) %>");
    $('#hidden_current_page').text("");
    $('#hidden_url').text("");
    $(".next").hide();
<% else %>
    $(".next").hide();
<% end %>

<% if @deal_emails.blank? %>
  $('#no_records').fadeIn(1000);
  $('a.next').hide();
<% else %>
  $('#no_records').hide();
<% end %>

$('.rating_stars').stars({
  inputType: "select"
});